version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tu-usuario
      MONGO_INITDB_ROOT_PASSWORD: tu-contraseña
    volumes:
      - mongodb-data:/data/db

  tu-aplicacion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tu-aplicacion
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb-data: